title: Devops Girls
description: Home of Devops Girls, an initiative for teaching Devops to ladies

markdown: kramdown

collections:
  materials:
    output: true
    permalink: /:collection/:name

twitter_username: DevOpsGirls
github_username:  DevOpsGirls
